/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import SQLjava.*;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jason
 */
public class StoreMainInterface extends javax.swing.JPanel {

    DAO dao = new DAO();
    SQLFitness query = new SQLFitness();

    /**
     * Creates new form StoreMainInterface
     */
    public StoreMainInterface() {
        initComponents();
        showProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnView = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1022, 749));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setText("Store");
        lbTitle.setPreferredSize(new java.awt.Dimension(300, 35));

        javax.swing.GroupLayout pnViewLayout = new javax.swing.GroupLayout(pnView);
        pnView.setLayout(pnViewLayout);
        pnViewLayout.setHorizontalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnViewLayout.setVerticalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private int column = 4;
    private int row = 0;

    private void showProduct() {
        ArrayList<Object[]> courseList = query.getQuerySelectAll("ID, Name, Price, Members, CourseLimit", "course", "Status", "1");
        //Get the row and column of GridLayout
        if (courseList.size() <= 12) {
            row = 3;
        } else if (courseList.size() > 12) {
            row = (courseList.size() / column) + 1;
        }

        //Get the width of every panel box
        int boxWidth = pnView.getWidth() / column;
        for (int i = 0; i < (row * column); i++) {
            JPanel pnBox = new JPanel();
            pnBox.setPreferredSize(new Dimension(boxWidth - 15, 200));

            if (i < courseList.size()) {
                Object[] objects = courseList.get(i);
                pnBox.setBackground(Color.YELLOW);
                pnBox.setName(objects[0].toString());
                createProduct(pnBox, objects);
            }
            pnView.add(pnBox);
        }
        pnView.setLayout(new GridLayout(row, column, 5, 5));
    }
    
        private void createProduct(JPanel pnBox, Object[] objects) {
        JLabel lbTitle = new JLabel();
        lbTitle.setText(objects[1].toString());

        DefaultListModel listModel = new DefaultListModel();

        //Input every exercise name in to list
        showExercise(objects[0].toString(), listModel);
        showBook(objects[0].toString(), listModel);

        JList ltDetail = new JList(listModel);
        JScrollPane spDetail = new JScrollPane(ltDetail);

        JLabel lbMember = new JLabel();
        lbMember.setText("Member : " + objects[3] + "/" + objects[4]);
        
        JLabel lbPrice = new JLabel();
        lbPrice.setText("Price : " + objects[2]);

        JButton btBuy = new JButton();
        btBuy.setText("Buy");
        btBuy.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println(pnBox.getName());
                System.out.println(lbTitle.getText());
                
            }
        });

        setLayout(pnBox, lbTitle, spDetail, lbMember, lbPrice, btBuy);
    }

    private void showExercise(String courseId, DefaultListModel listModel) {
        String[] fieldName = new String[]{"exercise.Name"};
        String[] tableName = new String[]{"exercise", "coursedetail"};
        HashMap<String, String> conditionMap = new HashMap<>();
        conditionMap.put("exercise.ID", "coursedetail.ExerciseID");
        conditionMap.put("coursedetail.CourseID", courseId);

        ArrayList<Object[]> exerciseList = query.getQueryInner(fieldName, tableName, conditionMap);
        listModel.addElement("Exercise :");
        for (int i = 0; i < exerciseList.size(); i++) {
            Object[] exercise = exerciseList.get(i);
            listModel.addElement(" +  " + exercise[0].toString());
        }
    }

    private void showBook(String courseId, DefaultListModel listModel) {
        String[] fieldName = new String[]{"book.Name"};
        String[] tableName = new String[]{"book", "coursebook"};
        HashMap<String, String> conditionMap = new HashMap<>();
        conditionMap.put("book.ID", "coursebook.BookID");
        conditionMap.put("coursebook.CourseID", courseId);

        ArrayList<Object[]> bookList = query.getQueryInner(fieldName, tableName, conditionMap);
        listModel.addElement("Book :");
        for (int i = 0; i < bookList.size(); i++) {
            Object[] book = bookList.get(i);
            listModel.addElement(" + " + book[0].toString());
        }
    }
    
    private void setLayout(JPanel pnBox, JLabel lbTitle, JScrollPane spDetail, JLabel lbMember, JLabel lbPrice, JButton btBuy) {
        GroupLayout groupLayout = new GroupLayout(pnBox);
        pnBox.setLayout(groupLayout);
        groupLayout.setAutoCreateGaps(true);
        groupLayout.setAutoCreateContainerGaps(true);

        groupLayout.setHorizontalGroup(
                groupLayout.createSequentialGroup()
                        .addGroup(groupLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                .addComponent(lbTitle)
                                .addComponent(spDetail)
                                .addComponent(lbMember, GroupLayout.Alignment.LEADING)
                                .addComponent(lbPrice, GroupLayout.Alignment.TRAILING)
                                .addComponent(btBuy)
                        )
        );
        groupLayout.setVerticalGroup(
                groupLayout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addComponent(spDetail)
                        .addGroup(groupLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lbMember)
                                .addComponent(lbPrice)
                        )
                        .addComponent(btBuy)
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnView;
    // End of variables declaration//GEN-END:variables
}
