/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order;

import SQLjava.DAO;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LH
 */
public class OrderEdit extends javax.swing.JPanel {

    /**
     * Creates new form OrderAdd
     */
    public OrderEdit() throws SQLException {
        initComponents();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labVoucherDate = new javax.swing.JLabel();
        labVoucherNo = new javax.swing.JLabel();
        txtVoucherNo = new javax.swing.JTextField();
        labCustomer = new javax.swing.JLabel();
        Course = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        voucherDate = new com.toedter.calendar.JDateChooser();
        jComboCustomer = new javax.swing.JComboBox<>();
        panelFooter = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtConfig = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jComboBoxPayment = new javax.swing.JComboBox<>();
        jComboEmployee = new javax.swing.JComboBox<>();
        PanelBody = new javax.swing.JScrollPane();
        tabOrderDetail = new javax.swing.JTable();

        labTitle.setText("ORDER TRANSACTIONS");

        labVoucherDate.setText("VouhcerDate");

        labVoucherNo.setText("VoucherNo");

        txtVoucherNo.setEditable(false);
        txtVoucherNo.setToolTipText("Can't Edit");
        txtVoucherNo.setEnabled(false);

        labCustomer.setText("Customer");

        Course.setText("Course");

        jComboBoxCourse.setEditable(true);
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBoxCourse.setEnabled(false);

        jComboCustomer.setEditable(true);
        jComboCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" - Select an Option - "}));
        jComboCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCustomerActionPerformed(evt);
            }
        });
        DAO conn = new DAO();
        ArrayList<ArrayList<Object>> result = new ArrayList<>();
        ArrayList<String> field = new ArrayList<String>();
        field.add("name");

        try {
            //  Block of code to try
            result = conn.select(field, "customer");
        }
        catch(Exception e) {
            //  Block of code to handle errors
        }
        for (ArrayList<Object> j : result) {
            for (Object i : j) {
                jComboCustomer.addItem((String)i);
            }
        }

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labVoucherDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voucherDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(txtVoucherNo, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(labTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Course))
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labVoucherDate)
                            .addComponent(labVoucherNo)
                            .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCustomer)
                            .addComponent(jComboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(voucherDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        jLabel18.setText("Payment");

        jLabel19.setText("Creater");

        jLabel20.setText("Config");

        jLabel21.setText("Total");

        txtAmount.setEnabled(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jComboBoxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Postpaid", "Credit Card", "Master Card", "Bank ATM" }));

        jComboEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" - Select an Option - "}));
        jComboEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEmployeeActionPerformed(evt);
            }
        });
        try {
            field.add("Name");
            //  Block of code to try
            result = conn.select(field, "employee");
        }
        catch(Exception e) {
            //  Block of code to handle errors
        }
        for (ArrayList<Object> j : result) {
            for (Object i : j) {
                jComboEmployee.addItem((String)i);
            }
        }

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFooterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel18, jLabel19, jLabel20, jLabel21, txtAmount, txtConfig});

        tabOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Course", "Service Name", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabOrderDetail.setToolTipText("You can't edit table order detail");
        tabOrderDetail.setEnabled(false);
        PanelBody.setViewportView(tabOrderDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBody, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEmployeeActionPerformed

    private void jComboCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCustomerActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String voucherno = txtVoucherNo.getText();
        DAO conn = new DAO();
        try {
            String table = "transaction";
            HashMap<String, Object> data = new HashMap<String, Object>();
            
            //data.put("VoucherNo", txtVoucherNo.getText());
            data.put("DateCreated", voucherDate.getDate());
            int customerID = getCustomerID(jComboCustomer.getSelectedItem());
            data.put("customerID", customerID);
            data.put("payment", jComboBoxPayment.getSelectedIndex());
            data.put("Creater", jComboEmployee.getSelectedIndex());
            data.put("Amount", txtAmount.getText());

            HashMap<String, Object> condition = new HashMap<String, Object>();
            condition.put("VoucherNo", voucherno);

            conn.Update(table, data, condition);

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed
    public int getCustomerID(Object customer) throws SQLException{
        DAO conn = new DAO();
        String str = "name = '"+customer+"'";
        return conn.selectGetID("customer",str);
    }
    public void addDataEdit() throws SQLException{
        System.out.println("voucher no order edit "+this.voucherno);
  
        System.out.println(" voucher no ordereidt(354)");
        if(this.voucherno!=null){
            // get data master
            
        DAO test = new DAO();
        ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
        Object[][] field = new Object[8][2];
        field[0][0] ="transaction"; field[0][1] ="voucherNo";
        field[1][0] ="transaction"; field[1][1] ="DateCreated"; 
        field[2][0] ="transaction"; field[2][1] ="Description";
        field[3][0] ="customer"; field[3][1] ="name"; 
        field[4][0] ="transaction"; field[4][1] ="Payment";
        field[5][0] ="transaction"; field[5][1] ="creater"; 
        field[6][0] ="transaction"; field[6][1] ="Amount";
        field[7][0] ="transaction"; field[7][1] ="Config"; 


        ArrayList<String> table = new ArrayList<String>();
        table.add("transaction");
        table.add("customer");

        HashMap<String, Object> on = new HashMap<String, Object>();
        on.put("transaction.CustomerID", "customer.id");

        String where = " transaction.voucherno = '"+this.voucherno+"'";
                        
        result = test.select(field, table,on,where);
        
        // set value master
        txtVoucherNo.setText((String) result.get(0).get(0));// voucherNo
         Date dateobj = new Date();
        voucherDate.setDate(dateobj);// voucherDate
        jComboCustomer.setSelectedItem(result.get(0).get(3));// customer
        jComboBoxPayment.setSelectedItem(result.get(0).get(4));//payment
        jComboEmployee.setSelectedItem(result.get(0).get(5));//creater - employee
        txtAmount.setText((String) result.get(0).get(6));//Amount
        txtConfig.setText((String) result.get(0).get(7));
                
        addOrderDetail(txtVoucherNo.getText());
        
        }// end check valueEidt
    }
    public void addOrderDetail(String voucherno){

        DAO test = new DAO();
        ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
        Object[][] field = new Object[4][2];
        field[0][0] ="orderdetail"; field[0][1] ="Course";
        field[1][0] ="orderdetail"; field[1][1] ="ProductName"; 
        field[2][0] ="orderdetail"; field[2][1] ="Description";
        field[3][0] ="orderdetail"; field[3][1] ="Price";

        ArrayList<String> table = new ArrayList<String>();
        table.add("transaction");
        table.add("orderdetail");

        HashMap<String, Object> on = new HashMap<String, Object>();
        on.put("transaction.id", "orderdetail.BatchID");

        String where = "transaction.voucherno ='"+voucherno+"'";
                        
        try {
            result = test.select(field, table,on,where);
        } catch (SQLException ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // add to taborderdetail
        addToTable(result,tabOrderDetail);
        
    }
    public void addToTable(ArrayList<ArrayList<Object>> result,JTable table){
         try {
            int row = result.size();

            int tableRow = table.getRowCount();
            int num = tableRow > 1 ? (int) table.getValueAt(0, 0) + 1 : 0;
            
            for (int i = 0; i < row; i++) {
                Object[] rowData = new Object[5];

//             for(int j=0;j<col;j++){
//                 Object value = result.get(i).get(j);
//                 rowData[j] =value;
//            }

                rowData[0] = i+1+num;
                rowData[1] = result.get(i).get(0); // course   
                rowData[2] = (String) result.get(i).get(1);// service name
                rowData[3] = result.get(i).get(2);// Description
                rowData[4] = result.get(i).get(3); // price
                
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(rowData);
            }

        } catch (Exception e) {
            System.out.println("error addTableOderDetail " + e);
        }
    }

    
     public void takeVoucherNo(String c) {
        this.voucherno = c;
    }
    private String voucherno;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Course;
    private javax.swing.JScrollPane PanelBody;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxPayment;
    private javax.swing.JComboBox<String> jComboCustomer;
    private javax.swing.JComboBox<String> jComboEmployee;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel labCustomer;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labVoucherDate;
    private javax.swing.JLabel labVoucherNo;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tabOrderDetail;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtConfig;
    private javax.swing.JTextField txtVoucherNo;
    private com.toedter.calendar.JDateChooser voucherDate;
    // End of variables declaration//GEN-END:variables

}
