/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fitness;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Jason
 */
public class FitnessDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form FitnessDetailPanel
     */
    public FitnessDetailPanel() {
        initComponents();
        chooseForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDetail = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(980, 640));

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseForm() {
        FitnessEditPanel fitnessEdit = new FitnessEditPanel();
        fitnessEdit.setBounds(0, 0, 980, 640);
        switch (FitnessMainPanel.tableName) {
            case "Course":
                Component[] courseComponent = fitnessEdit.pnCourseForm.getComponents();
                disableComponent(courseComponent);
                break;
            case "Package":
                Component[] packageComponent = fitnessEdit.pnPackageForm.getComponents();
                disableComponent(packageComponent);
                break;
            case "Exercise":
                Component[] exerciseComponent = fitnessEdit.pnExerciseForm.getComponents();
                disableComponent(exerciseComponent);
                break;
            case "Book":
                Component[] bookComponent = fitnessEdit.pnBookForm.getComponents();
                disableComponent(bookComponent);
                break;
        }
        pnDetail.add(fitnessEdit);
        pnDetail.setVisible(true);
    }
    
    private void disableComponent(Component[] components) {
        for (Component component : components) {
            if (component.toString().contains("JButton")) {
                component.setVisible(false);
            } else if (component.toString().contains("JScrollPane")) {
                JScrollPane temp = (JScrollPane) component;
                temp.getViewport().getView().setEnabled(false);
            }
            component.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnDetail;
    // End of variables declaration//GEN-END:variables
}
