/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Entities.*;
import SQLjava.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Viet
 */
public class CustomerEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberEditPanel
     */
    public CustomerEditPanel() {
        initComponents();
        starter(CustomerMainPanel.selectedId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnAvatar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCard = new javax.swing.JTextField();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnOther = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRollNo = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LayerService = new javax.swing.JLayeredPane();
        jLabel20 = new javax.swing.JLabel();
        txtPackageStart = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPackageExpiry = new javax.swing.JTextField();
        btnPackageTransfer = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnPackagePause = new javax.swing.JButton();
        btnPackageExtend = new javax.swing.JButton();
        btnPackageCancel = new javax.swing.JButton();
        btnPackageNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCourseStart = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtCourseExpiry = new javax.swing.JTextField();
        cbxPackage = new javax.swing.JComboBox<>();
        cbxCourse = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtPackageTotalDay = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtCourseTotalDay = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPackageLeft = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCourseLeft = new javax.swing.JTextField();
        btnCourseNew = new javax.swing.JButton();
        btnCourseEdit = new javax.swing.JButton();
        btnCoursePause = new javax.swing.JButton();
        btnCourseCancel = new javax.swing.JButton();
        dateBirth = new com.toedter.calendar.JDateChooser();

        setMaximumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(976, 658));

        jLabel11.setText("Avatar:");
        jLabel11.setPreferredSize(new java.awt.Dimension(102, 25));

        lblAvatar.setText("Image");
        lblAvatar.setPreferredSize(new java.awt.Dimension(200, 200));

        btnAvatar.setText("Change Avatar");
        btnAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvatar)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAvatar)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        jLabel3.setText("*Full Name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel13.setText("*Id Card/Passpord:");
        jLabel13.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel4.setText("Branch:");
        jLabel4.setPreferredSize(new java.awt.Dimension(102, 25));

        txtCard.setPreferredSize(new java.awt.Dimension(200, 25));

        rbtnMale.setText("Male");
        rbtnMale.setPreferredSize(new java.awt.Dimension(150, 25));

        rbtnFemale.setText("Female");

        rbtnOther.setText("Others");

        jLabel5.setText("*Gender:");
        jLabel5.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel15.setText("*Address:");
        jLabel15.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel6.setText("*Phone Number:");
        jLabel6.setPreferredSize(new java.awt.Dimension(102, 25));

        txtAddress.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel7.setText("*Email:");
        jLabel7.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel16.setText("Note:");
        jLabel16.setPreferredSize(new java.awt.Dimension(102, 25));

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        jLabel10.setText("*Membership Code:");
        jLabel10.setPreferredSize(new java.awt.Dimension(102, 25));

        txtMember.setEditable(false);
        txtMember.setEnabled(false);
        txtMember.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edit Customer");

        jLabel2.setText("Roll No:");
        jLabel2.setPreferredSize(new java.awt.Dimension(102, 25));

        txtRollNo.setEditable(false);
        txtRollNo.setEnabled(false);
        txtRollNo.setPreferredSize(new java.awt.Dimension(200, 25));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtFullName.setPreferredSize(new java.awt.Dimension(200, 25));

        txtPhone.setPreferredSize(new java.awt.Dimension(200, 25));

        txtEmail.setPreferredSize(new java.awt.Dimension(200, 25));

        txtBranch.setEditable(false);
        txtBranch.setEnabled(false);
        txtBranch.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel12.setText("*Date of Birth:");
        jLabel12.setPreferredSize(new java.awt.Dimension(102, 25));

        LayerService.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("Started Date:");
        jLabel20.setPreferredSize(new java.awt.Dimension(102, 25));

        txtPackageStart.setEnabled(false);
        txtPackageStart.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel21.setText("Expiry Date:");
        jLabel21.setPreferredSize(new java.awt.Dimension(102, 25));

        txtPackageExpiry.setEnabled(false);
        txtPackageExpiry.setPreferredSize(new java.awt.Dimension(200, 25));

        btnPackageTransfer.setText("Transfer Days");
        btnPackageTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageTransferActionPerformed(evt);
            }
        });

        jLabel25.setText("Package:");
        jLabel25.setPreferredSize(new java.awt.Dimension(102, 25));

        btnPackagePause.setText("Pause");
        btnPackagePause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackagePauseActionPerformed(evt);
            }
        });

        btnPackageExtend.setText("Extend");
        btnPackageExtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageExtendActionPerformed(evt);
            }
        });

        btnPackageCancel.setText("Cancel Service");
        btnPackageCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageCancelActionPerformed(evt);
            }
        });

        btnPackageNew.setText("Buy New");
        btnPackageNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageNewActionPerformed(evt);
            }
        });

        jLabel30.setText("Course:");
        jLabel30.setPreferredSize(new java.awt.Dimension(102, 25));

        jLabel32.setText("Started Date:");
        jLabel32.setPreferredSize(new java.awt.Dimension(102, 25));

        txtCourseStart.setEditable(false);
        txtCourseStart.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel33.setText("Expirry Date:");
        jLabel33.setPreferredSize(new java.awt.Dimension(102, 25));

        txtCourseExpiry.setEnabled(false);
        txtCourseExpiry.setPreferredSize(new java.awt.Dimension(200, 25));

        cbxPackage.setPreferredSize(new java.awt.Dimension(64, 25));

        cbxCourse.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel19.setText("Total Days:");
        jLabel19.setPreferredSize(new java.awt.Dimension(102, 25));

        txtPackageTotalDay.setEnabled(false);
        txtPackageTotalDay.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel31.setText("Total Days:");
        jLabel31.setPreferredSize(new java.awt.Dimension(102, 25));

        txtCourseTotalDay.setEnabled(false);
        txtCourseTotalDay.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel26.setText("Days Left:");
        jLabel26.setPreferredSize(new java.awt.Dimension(102, 25));

        txtPackageLeft.setEnabled(false);
        txtPackageLeft.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel27.setText("Days Left:");
        jLabel27.setPreferredSize(new java.awt.Dimension(102, 25));

        txtCourseLeft.setEnabled(false);
        txtCourseLeft.setPreferredSize(new java.awt.Dimension(200, 25));

        btnCourseNew.setText("Buy New");
        btnCourseNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseNewActionPerformed(evt);
            }
        });

        btnCourseEdit.setText("Schedule");
        btnCourseEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseEditActionPerformed(evt);
            }
        });

        btnCoursePause.setText("Pause");
        btnCoursePause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursePauseActionPerformed(evt);
            }
        });

        btnCourseCancel.setText("Cancel Service");
        btnCourseCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseCancelActionPerformed(evt);
            }
        });

        LayerService.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtPackageStart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtPackageExpiry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnPackageTransfer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnPackagePause, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnPackageExtend, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnPackageCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnPackageNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtCourseStart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtCourseExpiry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(cbxPackage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(cbxCourse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtPackageTotalDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtCourseTotalDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtPackageLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(txtCourseLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnCourseNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnCourseEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnCoursePause, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerService.setLayer(btnCourseCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayerServiceLayout = new javax.swing.GroupLayout(LayerService);
        LayerService.setLayout(LayerServiceLayout);
        LayerServiceLayout.setHorizontalGroup(
            LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerServiceLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LayerServiceLayout.createSequentialGroup()
                                .addComponent(btnCourseNew)
                                .addGap(18, 18, 18)
                                .addComponent(btnCourseEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnCoursePause)
                                .addGap(18, 18, 18)
                                .addComponent(btnCourseCancel))
                            .addGroup(LayerServiceLayout.createSequentialGroup()
                                .addComponent(cbxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCourseStart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtCourseExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCourseTotalDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCourseLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1)
                    .addGroup(LayerServiceLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cbxPackage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPackageStart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPackageExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPackageTotalDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPackageLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPackageNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnPackageExtend)
                        .addGap(18, 18, 18)
                        .addComponent(btnPackageTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPackagePause)
                        .addGap(18, 18, 18)
                        .addComponent(btnPackageCancel)))
                .addContainerGap())
        );
        LayerServiceLayout.setVerticalGroup(
            LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPackageStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPackageExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPackageTotalDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPackageLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPackagePause)
                        .addComponent(btnPackageTransfer)
                        .addComponent(btnPackageExtend)
                        .addComponent(btnPackageNew))
                    .addComponent(btnPackageCancel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseTotalDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LayerServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCoursePause)
                    .addComponent(btnCourseEdit)
                    .addComponent(btnCourseCancel)
                    .addComponent(btnCourseNew))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateBirth.setName("JDateBirth"); // NOI18N
        dateBirth.setPreferredSize(new java.awt.Dimension(200, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 327, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rbtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbtnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbtnOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(797, 797, 797)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LayerService)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(rbtnFemale)
                                                    .addComponent(rbtnOther))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LayerService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatarActionPerformed
        imagePath = ProjectLib.imgChooser(lblAvatar);
    }//GEN-LAST:event_btnAvatarActionPerformed

    private void btnPackageNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageNewActionPerformed

    }//GEN-LAST:event_btnPackageNewActionPerformed

    private void btnPackageExtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageExtendActionPerformed
        String productId = cbxPackage.getSelectedItem().toString();

    }//GEN-LAST:event_btnPackageExtendActionPerformed

    private void btnPackageTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageTransferActionPerformed
        int daysLeft = Integer.parseInt(txtPackageLeft.getText());

    }//GEN-LAST:event_btnPackageTransferActionPerformed

    private void btnPackagePauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackagePauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPackagePauseActionPerformed

    private void btnPackageCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPackageCancelActionPerformed

    private void btnCourseNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseNewActionPerformed

    }//GEN-LAST:event_btnCourseNewActionPerformed

    private void btnCourseEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseEditActionPerformed

    }//GEN-LAST:event_btnCourseEditActionPerformed

    private void btnCoursePauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursePauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoursePauseActionPerformed

    private void btnCourseCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerService;
    private javax.swing.JButton btnAvatar;
    private javax.swing.JButton btnCourseCancel;
    private javax.swing.JButton btnCourseEdit;
    private javax.swing.JButton btnCourseNew;
    private javax.swing.JButton btnCoursePause;
    private javax.swing.JButton btnPackageCancel;
    private javax.swing.JButton btnPackageExtend;
    private javax.swing.JButton btnPackageNew;
    private javax.swing.JButton btnPackagePause;
    private javax.swing.JButton btnPackageTransfer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxCourse;
    private javax.swing.JComboBox<String> cbxPackage;
    private com.toedter.calendar.JDateChooser dateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JRadioButton rbtnOther;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCard;
    private javax.swing.JTextField txtCourseExpiry;
    private javax.swing.JTextField txtCourseLeft;
    private javax.swing.JTextField txtCourseStart;
    private javax.swing.JTextField txtCourseTotalDay;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtPackageExpiry;
    private javax.swing.JTextField txtPackageLeft;
    private javax.swing.JTextField txtPackageStart;
    private javax.swing.JTextField txtPackageTotalDay;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRollNo;
    // End of variables declaration//GEN-END:variables

    //custom-code
    private int rollNo;
    private int membership;
    private String imagePath;

    private void starter(int rollNo) {
        this.rollNo = rollNo;
        DAOMember dao = new DAOMember();
        Customer customer = dao.selectCustomer(rollNo);
        txtRollNo.setText(String.valueOf(customer.getId()));
        txtBranch.setText(customer.getFullName());
        txtMember.setText(String.valueOf(customer.getMember()));
        txtFullName.setText(customer.getFullName());
        txtCard.setText(customer.getIdCard());
        dateBirth.setDate(customer.getBirthday());
        txtPhone.setText(String.valueOf(customer.getPhone()));
        switch (customer.getGender()) {
            case 1:
                rbtnMale.setSelected(true);
                break;
            case 2:
                rbtnFemale.setSelected(true);
                break;
            default:
                rbtnOther.setSelected(true);
                break;
        }
        txtEmail.setText(customer.getEmail());
        txtAddress.setText(customer.getAddress());
        txtNote.setText(customer.getNote());
        //ProjectLib.imgResize(customer.getAvatar(),lblAvatar);
    }
    //end custom-code
}
