/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Schedule;

import SQLjava.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viet
 */
public class ScheduleListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleListPane
     */
    public ScheduleListPanel() {
        initComponents();
        starter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schedulePanel = new javax.swing.JTabbedPane();
        mornPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMorning = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMornStart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMornEnd = new javax.swing.JTextField();
        noonPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNoon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNoonStart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoonEnd = new javax.swing.JTextField();
        evenPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEvening = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtEvenStart = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEvenEnd = new javax.swing.JTextField();

        tblMorning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Day", "Status", "Total Course", "Total Exercise", "Total Member", "Total Employee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMorning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMorningMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMorning);

        jLabel2.setText("Shift Starts:");
        jLabel2.setPreferredSize(new java.awt.Dimension(102, 25));

        txtMornStart.setEditable(false);

        jLabel3.setText("Shift Ends:");
        jLabel3.setPreferredSize(new java.awt.Dimension(102, 25));

        txtMornEnd.setEditable(false);

        javax.swing.GroupLayout mornPanelLayout = new javax.swing.GroupLayout(mornPanel);
        mornPanel.setLayout(mornPanelLayout);
        mornPanelLayout.setHorizontalGroup(
            mornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mornPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(mornPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMornStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMornEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 635, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mornPanelLayout.setVerticalGroup(
            mornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mornPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mornPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMornStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMornEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        schedulePanel.addTab("Moring", mornPanel);

        tblNoon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Day", "Total Course", "Total Exercise", "Total Member", "Total Employee", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNoon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNoon);

        jLabel4.setText("Shift Starts:");
        jLabel4.setPreferredSize(new java.awt.Dimension(102, 25));

        txtNoonStart.setEditable(false);

        jLabel5.setText("Shift Ends:");
        jLabel5.setPreferredSize(new java.awt.Dimension(102, 25));

        txtNoonEnd.setEditable(false);

        javax.swing.GroupLayout noonPanelLayout = new javax.swing.GroupLayout(noonPanel);
        noonPanel.setLayout(noonPanelLayout);
        noonPanelLayout.setHorizontalGroup(
            noonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(noonPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 635, Short.MAX_VALUE)))
                .addContainerGap())
        );
        noonPanelLayout.setVerticalGroup(
            noonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        schedulePanel.addTab("Noon", noonPanel);

        tblEvening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null},
                {null, "", "", null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Day", "Total Course", "Total Exercise", "Total Member", "Total Employee", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEvening.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEveningMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEvening);

        jLabel6.setText("Shift Starts:");
        jLabel6.setPreferredSize(new java.awt.Dimension(102, 25));

        txtEvenStart.setEditable(false);

        jLabel7.setText("Shift Ends:");
        jLabel7.setPreferredSize(new java.awt.Dimension(102, 25));

        txtEvenEnd.setEditable(false);

        javax.swing.GroupLayout evenPanelLayout = new javax.swing.GroupLayout(evenPanel);
        evenPanel.setLayout(evenPanelLayout);
        evenPanelLayout.setHorizontalGroup(
            evenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(evenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addGroup(evenPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEvenStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEvenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        evenPanelLayout.setVerticalGroup(
            evenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(evenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEvenStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEvenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        schedulePanel.addTab("Evening", evenPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schedulePanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schedulePanel)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMorningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMorningMouseClicked
        int row = tblMorning.getSelectedRow();
        ScheduleMainPanel.selectedId = Integer.parseInt(tblMorning.getValueAt(row, 0).toString());
        ScheduleMainPanel.tableName = "Morning";
    }//GEN-LAST:event_tblMorningMouseClicked

    private void tblNoonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoonMouseClicked
        int row = tblNoon.getSelectedRow();
        ScheduleMainPanel.selectedId = Integer.parseInt(tblNoon.getValueAt(row, 0).toString());
        ScheduleMainPanel.tableName = "Noon";    }//GEN-LAST:event_tblNoonMouseClicked

    private void tblEveningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEveningMouseClicked
        int row = tblEvening.getSelectedRow();
        ScheduleMainPanel.selectedId = Integer.parseInt(tblEvening.getValueAt(row, 0).toString());
        ScheduleMainPanel.tableName = "Evening";
    }//GEN-LAST:event_tblEveningMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel evenPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mornPanel;
    private javax.swing.JPanel noonPanel;
    public javax.swing.JTabbedPane schedulePanel;
    private javax.swing.JTable tblEvening;
    public javax.swing.JTable tblMorning;
    public javax.swing.JTable tblNoon;
    private javax.swing.JTextField txtEvenEnd;
    private javax.swing.JTextField txtEvenStart;
    private javax.swing.JTextField txtMornEnd;
    private javax.swing.JTextField txtMornStart;
    private javax.swing.JTextField txtNoonEnd;
    private javax.swing.JTextField txtNoonStart;
    // End of variables declaration//GEN-END:variables

    //custom-code
    ArrayList<ArrayList<Object>> sqlResult;
    Object id, name, day, shift, mornStart, mornEnd, noonStart, noonEnd, evenStart, evenEnd, status, totalCourse, totalMember, totalEmployee, totalExercise;
    public int rollNo;

    //fill table
    private void starter() {
        ArrayList<String> columnName = new ArrayList<>();
        columnName.add("ID");
        columnName.add("Name");
        columnName.add("Day");
        columnName.add("Shift");
        columnName.add("Start");
        columnName.add("End");
        columnName.add("Status");
        DAOSchedule dao = new DAOSchedule();
        sqlResult = dao.select(columnName, "schedule", "Status=1");
        DefaultTableModel mornModel = (DefaultTableModel) tblMorning.getModel();
        mornModel.setRowCount(0);
        DefaultTableModel noonModel = (DefaultTableModel) tblNoon.getModel();
        noonModel.setRowCount(0);
        DefaultTableModel evenModel = (DefaultTableModel) tblEvening.getModel();
        evenModel.setRowCount(0);
        sqlResult.forEach(i -> {
            id = i.get(0);
            name = i.get(1);
            day = i.get(2);
            shift = i.get(3);
            status = i.get(6);
            Object[] row;
            if (Integer.parseInt(status.toString()) == 0) {
                row = new Object[]{id, name, day, "Inactive"};
            } else {
                row = new Object[]{id, name, day, "Active"};
            }
            String txtShift = shift.toString();
            switch (txtShift) {
                case "Morning":
                    mornStart = i.get(4);
                    mornEnd = i.get(5);
                    mornModel.addRow(row);
                    break;
                case "Noon":
                    noonStart = i.get(4);
                    noonEnd = i.get(5);
                    noonModel.addRow(row);
                    break;
                case "Evening":
                    evenStart = i.get(4);
                    evenEnd = i.get(5);
                    evenModel.addRow(row);
                    break;
            }
        });
        txtMornStart.setText(mornStart.toString());
        txtMornEnd.setText(mornEnd.toString());
        txtAddActionPerformed();
    }

    //add listener change start time and end time
    private void txtAddActionPerformed() {
        schedulePanel.addChangeListener((ChangeEvent e) -> {
            switch (schedulePanel.getSelectedIndex()) {
                case 0:
                    txtMornStart.setText(mornStart.toString());
                    txtMornEnd.setText(mornEnd.toString());
                    break;
                case 1:
                    txtNoonStart.setText(noonStart.toString());
                    txtNoonEnd.setText(noonEnd.toString());
                    break;
                case 2:
                    txtEvenStart.setText(evenStart.toString());
                    txtEvenEnd.setText(evenEnd.toString());
                    break;
            }
        });
    }
    //end custom-code
}
