/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nutrient;

import Entities.ProjectLib;
import SQLjava.*;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason
 */
public class NutrientNewPanel extends javax.swing.JPanel {

    DAO dao = new DAO();
    SQLFitness sql = new SQLFitness();

    /**
     * Creates new form NutrientNewPanel
     */
    public NutrientNewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNutrientStatus = new javax.swing.ButtonGroup();
        bgDietStatus = new javax.swing.ButtonGroup();
        bgRecipeStatus = new javax.swing.ButtonGroup();
        pnChoose = new javax.swing.JPanel();
        btNutrientForm = new javax.swing.JButton();
        tbDietForm = new javax.swing.JButton();
        btRecipeForm = new javax.swing.JButton();
        lbFormTitle = new javax.swing.JLabel();
        pnMainForm = new javax.swing.JPanel();
        pnNutrientForm = new javax.swing.JPanel();
        lbNutrientNo = new javax.swing.JLabel();
        tfNutrientNo = new javax.swing.JTextField();
        tfNutrientName = new javax.swing.JTextField();
        lbNutrientName = new javax.swing.JLabel();
        lbNutrientDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNutrientDescription = new javax.swing.JTextArea();
        btNutrientCreate = new javax.swing.JButton();
        pnDietForm = new javax.swing.JPanel();
        lbDietNo = new javax.swing.JLabel();
        tfDietNo = new javax.swing.JTextField();
        tfDietName = new javax.swing.JTextField();
        lbDietName = new javax.swing.JLabel();
        lbDietDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDietDescription = new javax.swing.JTextArea();
        btDietCreate = new javax.swing.JButton();
        pnRecipeForm = new javax.swing.JPanel();
        lbRecipeNo = new javax.swing.JLabel();
        tfRecipeNo = new javax.swing.JTextField();
        tfRecipeName = new javax.swing.JTextField();
        lbRecipeName = new javax.swing.JLabel();
        lbRecipeDescription = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taRecipeDescription = new javax.swing.JTextArea();
        btRecipeCreate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 640));

        pnChoose.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btNutrientForm.setText("Nutrient Form");
        btNutrientForm.setPreferredSize(new java.awt.Dimension(120, 40));
        btNutrientForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNutrientFormMouseClicked(evt);
            }
        });

        tbDietForm.setText("Diet Form");
        tbDietForm.setPreferredSize(new java.awt.Dimension(120, 40));
        tbDietForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDietFormMouseClicked(evt);
            }
        });

        btRecipeForm.setText("Recipe Form");
        btRecipeForm.setPreferredSize(new java.awt.Dimension(120, 40));
        btRecipeForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRecipeFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnChooseLayout = new javax.swing.GroupLayout(pnChoose);
        pnChoose.setLayout(pnChooseLayout);
        pnChooseLayout.setHorizontalGroup(
            pnChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChooseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRecipeForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbDietForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNutrientForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnChooseLayout.setVerticalGroup(
            pnChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChooseLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btNutrientForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tbDietForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btRecipeForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        lbFormTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbFormTitle.setPreferredSize(new java.awt.Dimension(400, 40));

        pnMainForm.setLayout(new java.awt.CardLayout());

        lbNutrientNo.setText("No :");
        lbNutrientNo.setPreferredSize(new java.awt.Dimension(80, 20));

        tfNutrientNo.setEnabled(false);
        tfNutrientNo.setPreferredSize(new java.awt.Dimension(100, 30));

        tfNutrientName.setPreferredSize(new java.awt.Dimension(300, 30));

        lbNutrientName.setText("Name :");
        lbNutrientName.setPreferredSize(new java.awt.Dimension(80, 20));

        lbNutrientDescription.setText("Description :");
        lbNutrientDescription.setPreferredSize(new java.awt.Dimension(80, 20));

        taNutrientDescription.setColumns(20);
        taNutrientDescription.setRows(5);
        jScrollPane1.setViewportView(taNutrientDescription);

        btNutrientCreate.setText("Create");
        btNutrientCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btNutrientCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNutrientCreateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnNutrientFormLayout = new javax.swing.GroupLayout(pnNutrientForm);
        pnNutrientForm.setLayout(pnNutrientFormLayout);
        pnNutrientFormLayout.setHorizontalGroup(
            pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNutrientFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNutrientFormLayout.createSequentialGroup()
                        .addComponent(lbNutrientNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNutrientNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNutrientFormLayout.createSequentialGroup()
                        .addComponent(lbNutrientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNutrientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNutrientFormLayout.createSequentialGroup()
                        .addComponent(lbNutrientDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNutrientCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        pnNutrientFormLayout.setVerticalGroup(
            pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNutrientFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNutrientNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNutrientNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNutrientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNutrientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnNutrientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNutrientDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btNutrientCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pnMainForm.add(pnNutrientForm, "card2");

        lbDietNo.setText("No :");
        lbDietNo.setPreferredSize(new java.awt.Dimension(80, 20));

        tfDietNo.setEnabled(false);
        tfDietNo.setPreferredSize(new java.awt.Dimension(100, 30));

        tfDietName.setPreferredSize(new java.awt.Dimension(300, 30));

        lbDietName.setText("Name :");
        lbDietName.setPreferredSize(new java.awt.Dimension(80, 20));

        lbDietDescription.setText("Description :");
        lbDietDescription.setPreferredSize(new java.awt.Dimension(80, 20));

        taDietDescription.setColumns(20);
        taDietDescription.setRows(5);
        jScrollPane2.setViewportView(taDietDescription);

        btDietCreate.setText("Create");
        btDietCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btDietCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDietCreateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDietFormLayout = new javax.swing.GroupLayout(pnDietForm);
        pnDietForm.setLayout(pnDietFormLayout);
        pnDietFormLayout.setHorizontalGroup(
            pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDietFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDietFormLayout.createSequentialGroup()
                        .addComponent(lbDietNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDietNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDietFormLayout.createSequentialGroup()
                        .addComponent(lbDietName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDietName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDietFormLayout.createSequentialGroup()
                        .addComponent(lbDietDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDietCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        pnDietFormLayout.setVerticalGroup(
            pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDietFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDietNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDietNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDietName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDietName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDietFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDietDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btDietCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pnMainForm.add(pnDietForm, "card2");

        lbRecipeNo.setText("No :");
        lbRecipeNo.setPreferredSize(new java.awt.Dimension(80, 20));

        tfRecipeNo.setEnabled(false);
        tfRecipeNo.setPreferredSize(new java.awt.Dimension(100, 30));

        tfRecipeName.setPreferredSize(new java.awt.Dimension(300, 30));

        lbRecipeName.setText("Name :");
        lbRecipeName.setPreferredSize(new java.awt.Dimension(80, 20));

        lbRecipeDescription.setText("Description :");
        lbRecipeDescription.setPreferredSize(new java.awt.Dimension(80, 20));

        taRecipeDescription.setColumns(20);
        taRecipeDescription.setRows(5);
        jScrollPane3.setViewportView(taRecipeDescription);

        btRecipeCreate.setText("Create");
        btRecipeCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btRecipeCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRecipeCreateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnRecipeFormLayout = new javax.swing.GroupLayout(pnRecipeForm);
        pnRecipeForm.setLayout(pnRecipeFormLayout);
        pnRecipeFormLayout.setHorizontalGroup(
            pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRecipeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRecipeFormLayout.createSequentialGroup()
                        .addComponent(lbRecipeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfRecipeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRecipeFormLayout.createSequentialGroup()
                        .addComponent(lbRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRecipeFormLayout.createSequentialGroup()
                        .addComponent(lbRecipeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRecipeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        pnRecipeFormLayout.setVerticalGroup(
            pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRecipeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRecipeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRecipeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRecipeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRecipeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRecipeCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pnMainForm.add(pnRecipeForm, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnMainForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnMainForm, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btNutrientCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNutrientCreateMouseClicked
        if (checkNutrient()) {
            String name = tfNutrientName.getText();
            String description = taNutrientDescription.getText();

            String tableName = "nutrient";
            HashMap<String, Object> nutrientData = new HashMap<>();
            nutrientData.put("Name", name);
            nutrientData.put("Description", description);
            if (dao.Insert(tableName, nutrientData)) {
                JOptionPane.showMessageDialog(null, "Nutrient Create Successful");
            } else {
                JOptionPane.showMessageDialog(null, "Nutrient Create Fault");
            }
        } else {
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_btNutrientCreateMouseClicked

    private void btNutrientFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNutrientFormMouseClicked
        nutrientForm();
    }//GEN-LAST:event_btNutrientFormMouseClicked

    public void nutrientForm() {
        pnMainForm.removeAll();
        pnMainForm.updateUI();
        pnMainForm.add(pnNutrientForm);
        lbFormTitle.setText("Nutrient Form");
        int no = sql.getQueryCountAll("nutrient");
        tfNutrientNo.setText(Integer.toString(no + 1));
    }

    private void tbDietFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDietFormMouseClicked
        pnMainForm.removeAll();
        pnMainForm.updateUI();
        pnMainForm.add(pnDietForm);
        lbFormTitle.setText("Diet Form");
        int no = sql.getQueryCountAll("diet");
        tfDietNo.setText(Integer.toString(no + 1));
    }//GEN-LAST:event_tbDietFormMouseClicked

    private void btDietCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDietCreateMouseClicked
        if (checkDiet()) {
            String name = tfDietName.getText();
            String description = taDietDescription.getText();

            String tableName = "diet";
            HashMap<String, Object> dietData = new HashMap<>();
            dietData.put("Name", name);
            dietData.put("Description", description);
            if (dao.Insert(tableName, dietData)) {
                JOptionPane.showMessageDialog(null, "Diet Create Successful");
            } else {
                JOptionPane.showMessageDialog(null, "Diet Create Fault");
            }
        } else {
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_btDietCreateMouseClicked

    private void btRecipeCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRecipeCreateMouseClicked
        if (checkRecipe()) {
            String name = tfRecipeName.getText();
            String description = taRecipeDescription.getText();

            String tableName = "recipe";
            HashMap<String, Object> dietData = new HashMap<>();
            dietData.put("Name", name);
            dietData.put("Description", description);
            if (dao.Insert(tableName, dietData)) {
                JOptionPane.showMessageDialog(null, "Recipe Create Successful");
            } else {
                JOptionPane.showMessageDialog(null, "Recipe Create Fault");
            }
        } else {
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_btRecipeCreateMouseClicked

    private void btRecipeFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRecipeFormMouseClicked
        pnMainForm.removeAll();
        pnMainForm.updateUI();
        pnMainForm.add(pnRecipeForm);
        lbFormTitle.setText("Recipe Form");
        int no = sql.getQueryCountAll("recipe");
        tfRecipeNo.setText(Integer.toString(no + 1));
    }//GEN-LAST:event_btRecipeFormMouseClicked

    private boolean checkNutrient() {
        boolean result = true;
        error = "";
        if ("".equals(tfNutrientName.getText())) {
            error += "Name field can no empty\n";
        } else if (!ProjectLib.checkRegExp(tfNutrientName.getText(), "productName")) {
            error += "Name field invalid\n";
        }
        if ("".equals(taNutrientDescription.getText())) {
            error += "Description field can no empty\n";
        }
        if (!"".equals(error)) {
            result = false;
        }
        return result;
    }
    
    private boolean checkDiet() {
        boolean result = true;
        error = "";
        if ("".equals(tfDietName.getText())) {
            error += "Name field can no empty\n";
        } else if (!ProjectLib.checkRegExp(tfDietName.getText(), "productName")) {
            error += "Name field invalid\n";
        }
        if ("".equals(taDietDescription.getText())) {
            error += "Description field can no empty\n";
        }
        if (!"".equals(error)) {
            result = false;
        }
        return result;
    }
    
    private boolean checkRecipe() {
        boolean result = true;
        error = "";
        if ("".equals(tfRecipeName.getText())) {
            error += "Name field can no empty\n";
        } else if (!ProjectLib.checkRegExp(tfRecipeName.getText(), "productName")) {
            error += "Name field invalid\n";
        }
        if ("".equals(taRecipeDescription.getText())) {
            error += "Description field can no empty\n";
        }
        if (!"".equals(error)) {
            result = false;
        }
        return result;
    }

    //Variables Zone
    private String error = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDietStatus;
    private javax.swing.ButtonGroup bgNutrientStatus;
    private javax.swing.ButtonGroup bgRecipeStatus;
    private javax.swing.JButton btDietCreate;
    private javax.swing.JButton btNutrientCreate;
    private javax.swing.JButton btNutrientForm;
    private javax.swing.JButton btRecipeCreate;
    private javax.swing.JButton btRecipeForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDietDescription;
    private javax.swing.JLabel lbDietName;
    private javax.swing.JLabel lbDietNo;
    private javax.swing.JLabel lbFormTitle;
    private javax.swing.JLabel lbNutrientDescription;
    private javax.swing.JLabel lbNutrientName;
    private javax.swing.JLabel lbNutrientNo;
    private javax.swing.JLabel lbRecipeDescription;
    private javax.swing.JLabel lbRecipeName;
    private javax.swing.JLabel lbRecipeNo;
    private javax.swing.JPanel pnChoose;
    private javax.swing.JPanel pnDietForm;
    private javax.swing.JPanel pnMainForm;
    private javax.swing.JPanel pnNutrientForm;
    private javax.swing.JPanel pnRecipeForm;
    private javax.swing.JTextArea taDietDescription;
    private javax.swing.JTextArea taNutrientDescription;
    private javax.swing.JTextArea taRecipeDescription;
    private javax.swing.JButton tbDietForm;
    private javax.swing.JTextField tfDietName;
    private javax.swing.JTextField tfDietNo;
    private javax.swing.JTextField tfNutrientName;
    private javax.swing.JTextField tfNutrientNo;
    private javax.swing.JTextField tfRecipeName;
    private javax.swing.JTextField tfRecipeNo;
    // End of variables declaration//GEN-END:variables
}
